#!/usr/bin/python3

# Copyright (C) 2015 DrEstebon

# This file is part of Papageorge.
#
# Papageorge is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Papageorge is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Papageorge If not, see <http://www.gnu.org/licenses/>.

import os, sys
import urwid, gi, cairo

if urwid.version.VERSION < (1,2,0):
    sys.exit('ERROR: you need urwid v1.2.0 or later')

if gi.version_info < (3,14,0):
    sys.exit('ERROR: you need PyGObject v3.14 or later')

if cairo.version_info < (1,10,0):
    sys.exit('ERROR: you need Pycairo v1.10 or later')

this_dir = os.path.dirname(os.path.abspath(__file__))
if os.path.isdir(os.path.join(this_dir, "lib/papageorge")) and \
        os.path.join(this_dir, "lib") not in sys.path:
    sys.path = [os.path.join(this_dir, "lib")] + sys.path

from getpass import getpass
import papageorge
import papageorge.config as config

if __name__ == "__main__":
    if len(sys.argv) > 2:
        config.fics_user, fics_pass = sys.argv[1:3]
    elif config.fics_user:
        if config.fics_pass:
            fics_pass = config.fics_pass
        else:
            fics_pass = ''
    else:
        config.fics_user = input('user (hit enter to login as guest): ')
        if config.fics_user != 'guest' and len(config.fics_user) > 0:
            fics_pass = getpass('pass: ')
        else:
            config.fics_user = 'guest'
            fics_pass = ''

    print('{} {}'.format(config.fics_user, fics_pass))

    papageorge.run(config.fics_user, fics_pass)

